---
# Monit handlers

- name: Restart Monit
  systemd:
    name: monit
    state: restarted
  become: yes

- name: Reload Monit configuration
  shell: monit reload
  become: yes

- name: Reload systemd daemon
  systemd:
    daemon_reload: yes
  become: yes
